include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # allow having TODOs in the code
    todo: ignore

linter:
  rules:
    avoid_print: false
    use_build_context_synchronously: false
