name: testapp
description: A new Flutter application.

version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.0.4
  photo_manager: 1.0.1 # Using this to generate a single `Podfile`.

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/something/
