name: TestApp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartx: ^0.2.0
  extended_text: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: 0.12.6

flutter:
  uses-material-design: true
