name: testapp
description: A new Flutter application.
version: 1.0.0+3
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.3.2
  photo_manager: ^1.3.1 # Using this to generate a single `Podfile`.

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/something/
