name: testapp
description: A new Flutter application.

version: 1.0.0+2

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  extended_text: any
  flutter_common_exports:
    git:
      url: https://github.com/AlexVincent525/flutter_common_exports.git
  path_provider: ^1.6.9
  provider: ^4.1.2
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  ff_annotation_route: ^3.2.0

flutter:
  uses-material-design: true
