// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  '/categories-page',
  '/custom-page-view-indicator-page',
  '/looks-like-sliver-appbar-page',
  '/test-inner-shadow-page',
  '/test-map-notify-page',
  '/test-scaffold-resize-page',
  '/test-selector-page',
  '/test-stack-tabbarview-page',
  '/text-field-in-floating-action-button-page',
  '/will-pop-scope-page',
];

class Routes {
  const Routes._();

  /// '分类页'
  ///
  /// [name] : '/categories-page'
  ///
  /// [routeName] : '分类页'
  static const String categoriesPage = '/categories-page';

  /// '自定义pageview indicator测试页'
  ///
  /// [name] : '/custom-page-view-indicator-page'
  ///
  /// [routeName] : '自定义pageview indicator测试页'
  static const String customPageViewIndicatorPage =
      '/custom-page-view-indicator-page';

  /// 'SliverAppBar测试页'
  ///
  /// [name] : '/looks-like-sliver-appbar-page'
  ///
  /// [routeName] : 'SliverAppBar测试页'
  static const String looksLikeSliverAppbarPage =
      '/looks-like-sliver-appbar-page';

  /// '内部阴影测试页'
  ///
  /// [name] : '/test-inner-shadow-page'
  ///
  /// [routeName] : '内部阴影测试页'
  static const String testInnerShadowPage = '/test-inner-shadow-page';

  /// 'Map notify测试页'
  ///
  /// [name] : '/test-map-notify-page'
  ///
  /// [routeName] : 'Map notify测试页'
  static const String testMapNotifyPage = '/test-map-notify-page';

  /// 'Scaffold大小变化测试页'
  ///
  /// [name] : '/test-scaffold-resize-page'
  ///
  /// [routeName] : 'Scaffold大小变化测试页'
  static const String testScaffoldResizePage = '/test-scaffold-resize-page';

  /// 'Selector测试页'
  ///
  /// [name] : '/test-selector-page'
  ///
  /// [routeName] : 'Selector测试页'
  static const String testSelectorPage = '/test-selector-page';

  /// '测试TabBarView'
  ///
  /// [name] : '/test-stack-tabbarview-page'
  ///
  /// [routeName] : '测试TabBarView'
  static const String testStackTabbarviewPage = '/test-stack-tabbarview-page';

  /// 'TextField与FAB测试页'
  ///
  /// [name] : '/text-field-in-floating-action-button-page'
  ///
  /// [routeName] : 'TextField与FAB测试页'
  static const String textFieldInFloatingActionButtonPage =
      '/text-field-in-floating-action-button-page';

  /// 'pop拦截测试页'
  ///
  /// [name] : '/will-pop-scope-page'
  ///
  /// [routeName] : 'pop拦截测试页'
  static const String willPopScopePage = '/will-pop-scope-page';
}
