// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/widgets.dart';

import 'pages/categories_page.dart';
import 'pages/custom_page_indicator_page.dart';
import 'pages/looks_like_sliver_appbar.dart';
import 'pages/test_inner_shadow_page.dart';
import 'pages/test_map_notify.dart';
import 'pages/test_progress_bar.dart';
import 'pages/test_scaffold_resize_page.dart';
import 'pages/test_selector_page.dart';
import 'pages/test_tabbar_view_page.dart';
import 'pages/textfield_as_fab_page.dart';
import 'pages/will_pop_scope_page.dart';

// ignore_for_file: argument_type_not_assignable
RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  switch (name) {
    case '/categories-page':
      return RouteResult(
        name: name,
        widget: CategoriesPage(),
        routeName: '分类页',
      );
    case '/custom-page-view-indicator-page':
      return RouteResult(
        name: name,
        widget: CustomPageViewIndicatorPage(),
        routeName: '自定义pageview indicator测试页',
      );
    case '/looks-like-sliver-appbar-page':
      return RouteResult(
        name: name,
        widget: LooksLikeSliverAppBarPage(),
        routeName: 'SliverAppBar测试页',
      );
    case '/test-inner-shadow-page':
      return RouteResult(
        name: name,
        widget: TestInnerShadowPage(),
        routeName: '内部阴影测试页',
      );
    case '/test-map-notify-page':
      return RouteResult(
        name: name,
        widget: TestSelectorPage(),
        routeName: 'Map notify测试页',
      );
    case '/test-progress-bar':
      return RouteResult(
        name: name,
        widget: ProgressBarPage(),
        routeName: 'Custom progress bar',
      );
    case '/test-scaffold-resize-page':
      return RouteResult(
        name: name,
        widget: TestScaffoldResizePage(),
        routeName: 'Scaffold大小变化测试页',
      );
    case '/test-selector-page':
      return RouteResult(
        name: name,
        widget: TestSelectorPage(),
        routeName: 'Selector测试页',
      );
    case '/test-stack-tabbarview-page':
      return RouteResult(
        name: name,
        widget: TestTabBarViewPage(),
        routeName: '测试TabBarView',
      );
    case '/text-field-in-floating-action-button-page':
      return RouteResult(
        name: name,
        widget: TextFieldInFloatingActionButtonPage(),
        routeName: 'TextField与FAB测试页',
      );
    case '/will-pop-scope-page':
      return RouteResult(
        name: name,
        widget: WillPopScopePage(),
        routeName: 'pop拦截测试页',
      );
    default:
      return const RouteResult(name: 'flutterCandies://notfound');
  }
}

class RouteResult {
  const RouteResult({
    @required this.name,
    this.widget,
    this.showStatusBar = true,
    this.routeName = '',
    this.pageRouteType,
    this.description = '',
    this.exts,
  });

  /// The name of the route (e.g., "/settings").
  ///
  /// If null, the route is anonymous.
  final String name;

  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  /// The extend arguments
  final Map<String, dynamic> exts;
}

enum PageRouteType {
  material,
  cupertino,
  transparent,
}
